version: "2"
services:
  jsonserver:
    build: "mock-services"
    ports:
      - "3001:3001"
  db:
    build: "postgres-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=coder
      - POSTGRES_MULTIPLE_DATABASES=projectsdb,projectsdb_test
  esearch:
    image: "elasticsearch:2.3"
    ports:
      - "9200:9200"
      - "9300:9300"
  queue:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"