branch-defaults:
  dev:
    ec2_keyname: topcoder-dev-vpc-app
    environment: project-api-v4-dev
    group_suffix: null
  master:
    ec2_keyname: topcoder-prod-vpc-app
    environment: project-api-v4-prod
    group_suffix: null
  release:
    ec2_keyname: topcoder-qa-vpc-app
    environment: project-api-v4-dev
    group_suffix: null
    profile: tc-qa
global:
  application_name: tc-project-api
  default_ec2_keyname: topcoder-dev-vpc-app
  default_platform: Docker 1.9.1
  default_region: us-east-1
  profile: null
  sc: git
